name: flutter_ecommerce
description: A full-featured e-commerce app UI built with Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.0
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
